InnoWebLabs/Vehigo

src/pages/about.html

Added access of contact page from about page.
Earlier when we were in About us page, and click on the contact link in the footer section, it takes us nowhere. But now as link to contact page is added, now it takes us to contact page.
fixed #114 
Link to the contact page is now added.
##Screenshot
Now after going to contact in about us page, it shows this page

Added access of contact page from about page

---

assets/css/style.css

fix(CSS): Correct footer column alignment
This pull request resolves a UI bug where the columns in the site footer were visually misaligned. The issue was most noticeable with the last column, which was taking up an incorrect amount of space, causing an unbalanced layout.
This fix directly adjusts the CSS width percentages for the final footer column in both the default and dark-mode stylesheets to ensure all footer content is visually aligned and appears evenly spaced.
Fixes #126
[x] Modified the width of .footer-list:last-of-type from 50% to 17.33% in the main stylesheet.
[x] Adjusted the width of the same element from 33.33% to 15.33% in the dark-mode styles to match the alignment.
Before: Large Desktop 
After: Large Desktop 
Before: Tablet
After: Tablet
Before: Mobile
After: Mobile

fix(CSS): Correct footer column alignment-126

---

src/index.html
tandc.html

Fixed the Links in T&C page and Footer Sections of Home page :
1) Fixed the Wrong link of Home Page, in T&C navbar.
2) Fixed the non-linking of Explore page, in T&C navbar.
3) Fixed the non-linking of About Us page, in T&C navbar.
4) Fixed the non-linking of Blog page, in T&C navbar.
5) Fixed the non-linking of T&C page, in Footer section of Home page.
6) Fixed the non-linking of Contact Us page, in Footer section of Home page.
7) Fixed the non-linking of Blog page, in Footer section of Home page.
8) Fixed the non-linking of About Us page in Footer section of Home page.

Fixed the Links in T&C page and Footer Sections of Home page

---

offline.html

Fixed the following Navbar Links of offline.html :
1. Index was opening wrong Index Page.
2. Featured cars page linked.
3. About Us page linked.
4.  Blog page linked.

Fixed Navbar Links of offline.html

---

src/pages/about.html

Fixed Bug and Navbar of About Us
Before :
After :

Fixed Bug and Navbar of About Us

---

assets/css/style.css
offline.html

fix: Ensure footer content is visible in dark mode on Offline Center page  
This pull request addresses a visibility issue in the footer section of the "Offline Center" page when dark mode is enabled.  
Previously, the footer text and icons blended into the background due to incorrect or missing color styles for dark mode, making the content difficult or impossible to read.  
The fix ensures that the footer text, links, and icons have appropriate color contrast in dark mode, maintaining visual consistency and accessibility across the site.  
Fixes #241

Fix Footer of Offline-center page

---

ContactUs.html
accountpage.html
carPage.html
privacypolicy.html
src/index.html
src/pages/accountpage.html
src/pages/bill.html
src/pages/carPage.html
src/pages/trackPage.html
trackPage.html
vehigo-backend/accountpage.html

fix: Replace hardcoded 2023 with dynamic current year in footer
This pull request updates the Vehigo footer to display the current year dynamically instead of a hardcoded "2023". Previously, the footer always showed "2023", requiring manual updates each year.  
The change involves:
- Replacing the hardcoded year with a `<span>` element having `id="copyright-year"`.
- Adding a small JavaScript snippet that sets the text content of this span to the current year using `new Date().getFullYear()`.  
This ensures that the footer always shows the correct year automatically, improving maintainability and keeping the site up-to-date without manual intervention.
Closes #354
```html
<script>
const yearEl = document.getElementById('copyright-year');
if(yearEl) yearEl.textContent = new …
```

Added dynamic year functionality to footer on HTML pages

---

ContactUs.html
blog.html
hostPage.html
index.html
offline.html
preloader.css
preloader.js
rentcar.html
src/pages/about.html

✨ **feat: Add AOS animations and preloader to enhance UI/UX**  
This pull request integrates **AOS (Animate On Scroll)** animations across cards and sections of the website to create a smooth, engaging user experience. Additionally, it introduces an **animated pre-loader** on the landing page to make the initial load feel more interactive and modern.  
These improvements ensure the site no longer feels static and instead provides a visually dynamic flow as users scroll through content.  
Closes #411   
**Example:**  
| Before | After |  
|--------|-------|  
| ![Before](link-to-before-image) (it is the website url itself) | (After)(https://drive.google.com/file/d/1RZVNGmnsCmb01D_RYw6Uv3p5vwZw7dX0/view?usp=sharing) Video starts at 0:12 |

Pre-loader + AOS animations

---

offline.html
src/assets/styles/about.css
styles/offline.css

Description:
#405 
UNDER GSSOC25
This PR improves the layout of the Offline Centers page by fixing the uneven spacing between the boxes/cards displaying center details. Previously, the layout had unnecessary gaps which made it look unpolished and inconsistent.
Changes Made:
Updated CSS grid/flexbox properties for .card container.
Reduced extra margins and gaps to ensure even spacing.
Improved responsiveness across screen sizes (desktop, tablet, mobile).
Ensured cards are aligned consistently and maintain a clean layout.
Before:
Cards had inconsistent empty spaces between them.
Layout looked broken and uneven.
After:
Cards now have consistent spacing.
Layout appears balanced and polished.
Responsiveness maintained for all devices.

Fixed uneven spacing between Offline Centers boxes/cards

---

src/index.html

Fixed Home page Hover bug.
The Feature Card use to Come above the Navbar on Hover.
Before : 
After :

Fixed Home page Hover bug

---

index.html

Issue=font colour of text not visible in light mode
Solution= i changed it and now it is visible clearly
Corresponding issue= #667 
before 
after 
so review changes and assign this issue to me and give level 3 or 2 @Akashshelke07

Change font colour of text which is not visible in light mode

---

src/pages/help-center.html

This PR fixes the broken footer quick links in the help center page by correcting relative path references. All navigation links now properly redirect to their intended destinations.
The footer quick links in `src/pages/help-center.html` were not working due to incorrect relative path references, causing 404 errors and poor user experience.
Updated all footer and header navigation links to use correct relative paths based on the file's location in `src/pages/`.
1. **Company Section**:
- `about.html` → `../../src/pages/about.html`
- `pricing.html` → `../../src/pages/pricing.html`
- Blog and Contact Us links were already correct
2. **Support Section**:
- `Askaques.html` → `../../src/pages/Askaques.html`
- Other links were already correct
3. **Services Section**:
- `login.html` → …

Fix footer quick links in help-center.html

---

src/pages/bill.html

- Closes #783 
The header navigation link to blog.html on the bill.html page was broken, preventing users from accessing the blog. Fixing this improves navigation consistency and user experience.
Corrected the href path in the bill.html header so that the Blog link properly redirects to blog.html.
Yes, tested locally by opening bill.html in the browser and confirming the Blog link redirects to blog.html.
Yes, users can now successfully navigate to the Blog page from the header on bill.html.

Made the blog.html link working in bill.html

---

offline.html

- Closes #801
The offline-centres.html page had two key usability issues:
- Header links were not visible in light mode, making navigation difficult.
- The dark mode toggle button was present but not functional, preventing users from switching between modes.
- Fixed header link styling to ensure visibility in light mode.
- Updated dark mode toggle logic so that it correctly applies theme changes across the entire page, including header and content.
Yes, the changes were tested manually by:
- Switching between light and dark mode to confirm proper styling.
- Verifying that header links are visible and accessible in both modes.
Yes, users can now clearly see header links in light mode, and the dark mode toggle works correctly across the entire offline-centres.html page.

Made the header visible and implemented dark mode in Offline Centres page

---

.vscode/settings.json
SECURITY_IMPROVEMENTS.md
assets/css/accessibility-improvements.css
index.html

This PR addresses critical security vulnerabilities, accessibility issues, and performance optimizations to improve the overall quality and user experience of the VehiGo website.
- **Fixed External Link Security**: Added `rel="noopener noreferrer"` to all external social media links to prevent reverse tabnabbing attacks
- **Enhanced Privacy**: Prevents referrer information leakage to external sites
- **Compliance**: Follows modern web security best practices
- **Skip Navigation**: Added skip link for screen readers and keyboard users to jump directly to main content
- **Enhanced Focus Management**: Implemented visible focus indicators for all interactive elements
- **High Contrast Mode Support**: Added CSS media queries for `prefers-contrast: high`
- **Reduced Motion Support**: Added CSS …

🔒♿🚀 Security, Accessibility & Performance Improvements

---

ContactUs.html

Closes #846 
The theme toggler button labels were inverted:
- Clicking on **Dark** applied **Light theme**
- Clicking on **Light** applied **Dark theme**
This was confusing for users as the button text did not match the theme action.  
This PR fixes the toggler so that the button label always represents the **next available theme**.
- Updated the theme toggle logic in JavaScript.
- Ensured that when the site is in Light mode, the button shows **Dark**, and vice versa.
- Verified consistency of the toggle button across pages.
-Tested manually in the browser for both Light and Dark themes.
-Verified switching works correctly across multiple toggles.
- Yes, the **theme toggle button now works correctly**:
- Shows the correct label.
- Provides a consistent user experience.
**Screenshots …

 [Bug Fix] Fixed inverted theme toggler labels

---

sitemap.html

- Closes #832 
On the sitemap.html page, the header navigation links were not visible in light mode, making navigation inconsistent compared to other pages. This fix ensures proper visibility and consistent user experience across themes.
- Updated the header link styles on sitemap.html to ensure visibility in light mode.
- Aligned the navigation styling with the rest of the site for consistency.
Manually tested in both light mode and dark mode to confirm header links are clearly visible and consistent.
Yes. Users can now clearly see and use the header links in light mode on the sitemap.html page, improving navigation and accessibility.

Made Header Links Visible in Light Mode

---

index.html

Issue=sitemap not redirect correctly in homepage
Solution= i changes it and now redirect correctly
https://github.com/user-attachments/assets/0e775c6a-55ce-4e4a-9f2a-00c4b48a198d
before 
https://github.com/user-attachments/assets/69848679-58db-4343-8dd8-5ddfd0c36fd6
after
so find issue and corresponding changes and assign this pr to me and give level 3 or 2 @Akashshelke07

changed redirect error in homapage

---

ContactUs.css
ContactUs.html
ContactUs.js

Enhanced the contact form with comprehensive client-side validation and improved accessibility features. This update provides users with immediate, helpful feedback when filling out the form, making it more user-friendly and reducing submission errors.
This enhancement improves the overall user experience of the contact form, addressing potential usability issues where users might submit invalid data without knowing what went wrong.
Tested the form with various inputs:
- Valid names, emails, and messages submit successfully
- Invalid inputs (short names, malformed emails, empty messages) show appropriate error messages
- Error messages clear when users correct their input
- Form works correctly in both light and dark modes
- Accessibility features verified (keyboard navigation, screen …

Improve Contact Form Validation and Accessibility

---

rentcar.html

- Closes #866
This change fixes the footer social media links on the Rent Car page to redirect to Vehigo's official company profiles instead of generic social media homepages. This provides a more professional user experience and ensures users are directed to the correct company accounts across all social media platforms.
- **`rentcar.html`**: Updated footer social media links to point to Vehigo company profiles
- **Facebook**: Updated from `https://www.facebook.com` to `https://www.facebook.com/vehigo`
- **Instagram**: Updated from `https://www.instagram.com` to `https://www.instagram.com/vehigo`
- **X (Twitter)**: Updated from `https://www.twitter.com` to `https://x.com/vehigo`
- **LinkedIn**: Updated from `https://www.linkedin.com` to `https://www.linkedin.com/company/vehigo`
- …

Update Rent Car page footer social links to company profiles #866

---

blog.html
src/pages/Askaques.html

#877 fixed
**Changes Made:**
- Updated all social media links in the footer of `Askaques.html` to point to the company's official profiles:
- Facebook → https://facebook.com/vehigo
- Instagram → https://www.instagram.com/vehigo/
- X (Twitter) → https://twitter.com/vehigo
- LinkedIn → https://linkedin.com/company/vehigo
- GitHub → https://github.com/vehigo
- Added `target="_blank"` and `rel="noopener noreferrer"` to all links for better UX and security.
- Verified hover effects and styling remain consistent with the rest of the site.

Footer social links on Askaques page redirect to company profiles (#877)

---

blog.html

#876 fixed 
- Added social media icons (Facebook, Twitter, Instagram, LinkedIn, GitHub, Email).  
- Used Font Awesome icons for consistency.  
- Ensured links open in a new tab.

Add Social Media Icons to Blog Page (blog.html)

---

offline.html

- Closes #810 
---
Initially, I raised an issue to improve card spacing and alignment on the **Offline Centers** page.  
However, that enhancement was already implemented by another contributor.  
To further improve usability, I added a **search bar feature** that allows users to easily find service centers by city name.  
This change enhances the user experience by making the section more interactive and efficient.
---
- Added a **search input field** above the service center cards.
- Implemented **real-time JavaScript filtering** to display matching cards as users type.
- Added **CSS styling** for the search bar:
- Rounded edges and soft hover/focus shadows.
- Compatible with both light and dark themes.
- Ensured **responsive layout** for seamless viewing across devices.
- Verified that …

Added Search Bar to Offline Centers Page
