InnoWebLabs/Vehigo

assets/css/style.css

Changed the nav bar hover effect, to make it look perfect
Related to #29

updated nav-link hover #29

---

assets/css/style.css

corrected the mistake did to active instead of hover #29

---

assets/css/style.css

i have added new ui design to app.

Fix: Improved ui

---

blogs/blog1.html
blogs/blog2.html
blogs/blog3.html
blogs/blog4.html
blogs/blog5.html
index.html

- Replaced the static blog section with 5 real blogs.
-  Each blog opens in its own page with full content.
-  Added author, date, images, and improved layout.
-  All files are responsive and cleanly structured.
Please review and merge. Let me know if any changes are required.
**Issue #48** 
**Images**

Added 5 real blogs with full content and linked detail pages. Issue #48

---

styles/hostRegistration.css

https://github.com/user-attachments/assets/db08decd-c319-4649-908a-176f52ed6561
Enhanced form styling for a more elegant and consistent UI. Updated padding, font sizes, and button appearance for better usability.
Closes: #52

Enhanced form styling and improved UI with elegant color palette

---

offline.html
scripts/offline.js
styles/offline.css

Added an interactive Leaflet map showing offline service centers.
Below the map, added cards for each city with description and user rating.
A booking button was added at the bottom for users to schedule offline services.

Add offline map view with cards and booking button

---

index.html
tandc.html

Made the terms and condition page to work

added terms and conditions page

---

login.html
signup.html

Login branch

---

index.html

Solved Issue #75 as follows:
@Akashshelke07 please merge my PR.

Solved issue #75 -added company logo as favicon

---

index.html
src/pages/Askaques.html

Ask a question page added issue #37  is solved

Ask a question page added

---

index.html
src/index.html
src/pages/login.html

✅ Description of the Fix
This update fixes broken or non-functional navigation links in the website’s navbar. Previously, the href attributes in the <a> tags pointed to fragment identifiers like #, which did not redirect to valid or existing routes, resulting in a poor user experience.
Fixes implemented:
Ensured that all navigation links properly reflect the actual route structure of the application.

Fixed href tags

---

assets/css/style.css

Enhanced UI for input fields named Enter your location and Add an amount
Before it was looking like some label, only when you click on it, it shows outline of input field, but now without clicking over it, it is clearly visible that this is an input field.
fixes #113 
1. Inside assets/css/style.css the style of input-field class was modified.
2. Now it adds a border around input field all the times, which is visible even when not clicked on it.
**Example**:  
Before
After:

Enhanced UI for input fields

---

assets/css/style.css
index.html

-->change social links place 
--> added styles in back top top 
-->copyright text make in center
Example: ```feat: Add user authentication module``` or ```fix: Resolve login button responsiveness```
-->changes social link place from bottom footer section to top footer , it makes UI more interactive
-->remove duplicates nav for about us and blog
-->added animation effact and some other styles in back to top button
-->after removing social link from bottom footer -> make copyright in center
- [✔️] I have read the project's contributing guidelines.
- [✔️] My code follows the project's coding style and conventions.
- [✔️] I have performed a thorough self-review of my own code.
- [✔️] I have added comments to my code, …

solved issue #94 ,added social links to top footer from lower footer and added styles

---

assets/css/style.css
assets/js/script.js
index.html
login.html
package-lock.json
package.json
src/pages/Askaques.html
src/pages/about.html
src/pages/carPage.html
src/pages/hostPage.html
src/pages/tandc.html
src/pages/trackPage.html
vehigo-backend/.env.example
vehigo-backend/accountpage.html

Fixed issue #134
A concise and descriptive title for your pull request. Please follow Conventional Commits guidelines if applicable.
Example: ```feat: Add user authentication module``` or ```fix: Resolve login button responsiveness```
Provide a detailed description of the changes introduced by this pull request. Explain what was changed and why. Include any relevant context or design decisions.
Link any relevant issues from the Vehigo repository that this pull request addresses or is related to. Use keywords like Closes ```#ISSUE_NUMBER```, Fixes ```#ISSUE_NUMBER```, or Resolves ```#ISSUE_NUMBER``` to automatically close issues when the PR is merged.
List the specific changes implemented in this pull …

Fixed and created a newer version of dark mode

---

buy.html
buycar.js
buyscar.css
rentcar.html
sell.html
trackPage.html

#106 [Feature] Addes [x]
this feature enable user to buy car option is avaliable on rent car option it contain two option one for buying it and another for selling it selling feature is still under process and not added in this pr only buy option and minior bug fixes are being done 

#106 [Feature] Added Buy option for the user 

---

accountpage.html
carPage.html
feedbackForm.html
hostPage.html
src/index.html
src/pages/SelectionPage.html
src/pages/accountpage.html
src/pages/carPage.html
src/pages/feedbackForm.html
src/pages/hostPage.html
src/pages/login.html
src/pages/registrationPage copy.html
src/pages/registrationPage.html
src/pages/tandc.html

Description #116 
UNDER GSSOC2025 
This PR resolves a critical navigation inconsistency across the site where:
"About Us" links in the navbar and sidebar/menu pointed to different routes or components.
This led to confusion and inconsistent user experience.
✅ What Was Fixed
🔗 Unified all "About Us" links to consistently point to /about.html
📄 Standardized across navbar, sidebar, and mobile menus
🧭 Ensured consistent navigation behavior throughout the site
📂 Affected Files (14 total)

Standardize "About Us" Navigation Across All Pages

---

assets/css/loginstyle.css
src/assets/styles/loginstyle.css
src/pages/login.html

Summary
This PR revamps the Login page UI to align with the overall design system, providing a more modern, interactive, and accessible experience.
✅ What's Improved
🖼️ Background Enhancement
Added a high-resolution background image with a semi-transparent black overlay for contrast and aesthetic depth.
🖱️ Form Hover Scaling
Introduced a subtle scale-on-hover effect for the login form to improve focus and accessibility.
🎨 Styling Overhaul
Updated colors, spacing, typography, and layout for cleaner, brand-consistent design.
✨ Hover Interactivity
Added smooth hover transitions for inputs and buttons to enhance interactivity.
📱 Responsive Layout
Ensured proper rendering on mobile and desktop screens.
https://github.com/user-attachments/assets/bf7d5120-3da6-412a-9b3f-913f7df3795a

Redesigned Login Page UI for Better UX and Visual Appeal

---

src/pages/login.html

Problem :  Upon directly clicking on login , sign up buttons in their respective pages without filling any data (email,password etc) , it just stayed static without showing any pop up message like "must fill the these section". 
fix : #55 
I've made sure the login & sign up forms aren't directly submitted without entering all fields & added a pop up message asking user to fill the sections 
After 
- login page 
- signup page 
Please review it & let me know for any changes needed. Thank you!

Added Enhancements in Login Pages

---

ContactUs.html
assets/css/dark.css
assets/css/style.css
assets/js/script.js
index.html
login.html
offline.html
privacypolicy.html
rentcar.html
signup.html

feat: Add Login/Signup pages with synced light/dark theme support
This pull request introduces the Login and Signup pages into the project, including responsive UI forms and validation. Additionally, both pages now fully support light and dark themes, syncing correctly with the rest of the application based on the user's selected theme (stored in localStorage).
This enhances user experience by offering a consistent theme across all routes and introduces a foundational structure for authentication integration.
Closes #136  – Fix the UI of signup page
-Added Login and Signup pages with form fields and minimal validation
-Integrated theme toggle logic to apply correct theme on auth pages
-Ensured consistent layout and responsiveness across form components
-Used localStorage to persist theme …

Fixed signup/login page issue

---

assets/css/style.css
index.html
signup.html
src/pages/about.html

Solved issue #147 -Dark modeis now working on all pages:

Solved issue #147-Dark mode allpages

---

signup.html

Solved Issue #148 -fixed login page UI and added navbar and footer

Solved Issue#148-fixed login page UI and added navbar and footer

---

assets/css/style.css
assets/js/script.js
index.html

…ropdowns
Add client-side validation to search form inputs and dropdowns
This PR adds client-side validation to the homepage search form to improve user experience and prevent invalid submissions.
Specifically:
- Location input now checks for non-empty values.
- Rent input checks if it's a positive number.
- Dropdowns (Car Type, Transmission, Fuel Type) must be selected.
- Red borders and error messages are displayed for invalid fields.
This ensures users are properly guided when filling the form, reducing confusion and invalid searches.
Closes #141
List the specific changes implemented in this pull request. Be as specific as possible, referencing file paths or component names where appropriate.
Before …

Added Form Validation Feedback on Homepage Search

---

src/index.html

feat: Add filtering and sorting functionality for featured cars
Issue- 
#173
This pull request introduces filtering and sorting functionality for the featured cars section in [index.html](vscode-file://vscode-app/c:/Users/Asus/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html). Users can now filter cars based on type (SUV, Sedan, Hatchback) and location (Bhopal, Indore, Ujjain). Additionally, sorting options are available for price (Low to High, High to Low), model year, and ratings.
Changes:
Filtering Options:
-Dropdowns for car type and location.
Sorting Options:
-Dropdowns for sorting by price, model year, and ratings.
JavaScript Implementation:
-Added dynamic filtering and sorting logic to ensure seamless user experience. …

Added filtering and sorting  in the UI

---

src/assets/styles/about.css
src/pages/about.html

📌 Issue Summary
The About page lacked the global navigation/menu bar, which caused:
An inconsistent layout compared to other pages
No navigational access to main site sections
A disjointed experience, especially for new users
📎 Related Issue: #186 
🛠️ Fix Implemented
Imported and rendered the shared Navbar component at the top of the About page
Verified responsive behavior across screen sizes
Ensured consistent background, spacing, and padding
Adjusted layout to account for sticky/fixed header positioning (if applicable)

 Fix: Added Missing Global Navbar to About Page

---

index.html
src/index.html
src/pages/hostPage.html

Fixes: [Bug] Navbar Sections Not Navigating Properly on "Rent Your Car" Page
- Updated the `<nav>` section in `rentcar.html` to match `index.html`.
- Ensured all five navbar links are present and point to correct sections/pages:
- Home → `index.html`
- Explore Cars → `index.html#featured-car`
- About Us → `pages/about.html`
- Blog → `index.html#blog`
- Fare Calculator → `pages/bill.html`
- Previously, the navbar on the "Rent Your Car" page was missing or had incorrect links.
- This fix ensures consistent user navigation and resolves the mismatch across pages.
- All navbar links tested in the browser.
- Navigation and scroll behavior now work as expected.

🐞 Fix: Navbar Sections Not Navigating Properly on "Rent Your Car" Page

---

index.html
src/index.html
src/pages/hostPage.html

Description:
The current footer lacked visual clarity and structure, which could confuse users and reduce professionalism.
✅ Enhancement Made:
- Improved overall footer layout using better alignment and spacing
- Used semantic HTML structure for better accessibility
- Added text shadows and clean styling for improved readability
- Consistent styling with the rest of the site
🔗 Linked Issue:
Closes #183
🛠️ Final Steps:
Once you’ve pushed your branch, follow these:
Go to: https://github.com/abdey53/Vehigo

🎨 Enhanced Footer UI for Better Readability and Structure

---

src/index.html

**Added dynamic fetching of car details from Supabase.**
Issue : -#179
**Results-**
**Needed configuration:-**
**1. Create a table in supabase with following table schema.**
**2. Add this in your codebase.**

added supabase for dynamic fetching of details

---

offline.html

Solved Issue #165  -added map and offline centres in offline centres page:

Solved Issue #165 -added map and offline centres in offline centres page

---

CONTRIBUTING.md
README.md
assets/css/buy.css
buy.html
buycar.js
featured-car.html
index.html

-Dark mode button not working, not switching and not showing dark mode in features-car.html, modified featured-car.html to working dark-mode page ,below im attaching before and after image proofs, 
-Resolves issue no. : #215  
Thnks !
BEFORE 👎 :
AFTER 👍 :

Fixed : Fixed Dark mode button not working, not switching and not showing dark mode in features-car.html 

---

CONTRIBUTING.md
README.md
index.html

Added Dynamic current year fetching code mentioned under copyright & also fixed alt text wrong typo in one of tht car name tht toyata(crysta) one
Resolves issue : #208

Added : Dynamic current year fetching code mentioned under copyright & also fixed alt text wrong typo in one of tht car name

---

CONTRIBUTING.md
README.md
assets/css/buy.css
buy.html
buycar.js
index.html

Added buy.css for buy.html its so basic and not user friendly UI, so i have improved its UI add buy.css sepearately in asssets folder seperately also improved buycar.js asscociated with it, below is picture before and after improvement.
Resolves issue : #213 thanks!
BEFORE 👎 :
AFTER 👍:

Added & improved :added  buy.css for buy.html , improved buy.html page also enhanced buycar.js attached to it 

---

.vscode/launch.json
assets/css/feebackForm.css
featured-car.html
feedbackForm.html

Improved feedback form with proper css and functional components ,below pasting before and after page look..
BEFORE 👎 :
AFTER 👍 :

Improved: feedback form with proper css and functional components

---

signup.html

The Signup container's overflowing is solved, as shown below in the screenshot.
Before :
After :

Fixed Signup Container overflowing

---

login.html
signup.html
src/pages/login.html
styles/loginstyle.css

This pull request improves the signup form behavior by ensuring that:
The form cannot be submitted unless all required fields are filled.
A success message is displayed upon successful submission.
The form is reset after a successful submission.
These changes enhance user feedback and prevent incomplete form data from being submitted to the backend.
Fix : #195 
Added client-side validation to prevent form submission if any required field is empty.
Integrated a success message UI that is displayed upon a successful API response.
Implemented form reset logic after a successful signup.
<br>

Update SignUp Page Feature

---

README.md
buy.html
buyscar.css
index.html
login.html

Resolve hover effect issue.
Made changes in hover effect cause it was not visible.
Closes #222 
#223 
List the specific changes implemented in this pull request. Be as specific as possible, referencing file paths or component names where appropriate.
If your changes affect the UI or introduce visual features, include screenshots or GIFs to demonstrate the updates. Use a tool like [Loom](https://www.loom.com/) for recordings if needed.
Before:
After:

Fixed hover effect of "rent now"

---

accountpage.html
login.html

Fix: Redirection of blog and featured-cars in nav to actual information page
It's now working properly before that two options are of no use just to show on nav bar but now it works perfectly.
Closes: #236 
List the specific changes implemented in this pull request. Be as specific as possible, referencing file paths or component names where appropriate.
1.
Before:
After:
2.
Before:
After:

Redirect blog, featured-cars in the nav bar 

---

ContactUs.html

Fixed non working-links of Navbar in ContactUS Page.
About, Featured Cars and Blog buttons were not working.
Image :

Fixed non working-links of Navbar in ContactUS Page

---

ContactUs.css
ContactUs.html
rentcar.html
styles/rentcar.css

Fixed the Rentcar page bug. Also, Fixed Nav-bar and Content Overflowing Bug
Changes : 
1) Fixed the content overflowing
2) Fixed the Button overflowing
3) Changed Buttons style to make it attractive
4) Not proper Navbar 
5) Fixed Content Overflowing
Before :  ( Content not at the Centre )
After : 
Before : 
After : 
Before : 
After : 
Before : 
After :

Fixed Rentcar page Bug & Fixed Nav-bar and Content Overflowing Bug

---

ContactUs.html
SelectionPage.html
accountpage.html
blog.html
buy.html
carPage.html
featured-car.html
feedbackForm.html
hostPage.html
index.html
login.html
offline.html
registrationPage.html
rentcar.html
sell.html
signup.html
tandc.html
trackPage.html

Description:
It appears that the favicon is missing from the website. This affects brand recognition and may lead to confusion for users when multiple tabs are open. Please add or fix the favicon so it displays correctly in browser tabs.
Before : 
After : 
Issue #257 
Thankyou !

Add favicon

---

blogs/blog4.html
login.html
signup.html

Pull Request Template for Vehigo
1. Title
I changed login and register page because it show big logos in login page
2. Description
First when i touch on register buttonn it cannot   be touch and not redirect to login page what i do that i fix it redirect to login page and in login page big images are shown i fix it aslo and i make one more change i add profile section where user can logout their profile.
3. Related Issues
#280 
4. Changes Made
i remove all big logo and i make enhance login and register pages. I  made country because you cannot launch for only india and according to country code i set limit in digit of number like in india their are 10 digit number.
5. Checklist
6. Screenshots/GIFs
Login page before i …

Update login and signup pages UI

---

src/index.html
src/pages/about.html

📝 Description
This pull request introduces a fully designed and structured about.html page to the Vehigo project. The page highlights key information such as the mission of the platform, the team behind the project, and other relevant details aimed at providing users with deeper insight into the purpose and people of Vehigo.
In addition, this PR resolves a navigation issue where the "About" link in the navbar was previously misconfigured and redirected users back to the index.html (homepage) instead of the intended about section.
This fix ensures that users now have a seamless experience when navigating to the About page directly from the main navigation bar.
🔗 Related Issues
Fixes: #1815 ← (Replace with your actual issue number if applicable)
🔧 Changes Made
✅ Created a new about.html …

added about us page with the nice ui design

---

ContactUs.css
ContactUs.html

Fixed NavBar of Contact us Page
Before : 
After :

Fixed NavBar of Contact us Page

---

buy.html
login.html
sell.html
signup.html

1. Title
-Adding a sell car and buy a car feature 
2. Description
-when i touch on sell a car option one line written this feature available soon so i make this page and according to change buy now section
3. Related Issues
#311 
4. Changes Made
First i add car registration number and some details regarding to sell a car like model number, registration number, manufacturing year, car model, fual type, transmission, kilometer driven, car description, uploading car photo from all side like frond, back, left side, right side, engine bay, interior i attaching a photo and video of this one option is this owner and user can chat about cars and option is this 
- Added complete sell car form with photo upload
- Implemented mandatory field validation with visual feedback
- Created buy.html page to …

Add comprehensive sell car functionality and improved login validation

---

src/assets/styles/style.css
src/index.html

Fixed Filter section of Home page
Before : 
After :

Fixed Filter section of Home page

---

index.html
offline.html

1. Title
Update 'Rent now' buttons to redirect to rent your car button and in offline centre removed extra things which is visible in preview
2. Description
i changes the code and issue solved like when user touch on rent now button it is redirect to rent your car section and in offline center page their is some extra thing which is visible in live preview
3. Related Issus
#337 #339 
4. Changes Made
-i change the redirected link so that when user touch on rent now button it is redirect to rentyourcar.html
-i removed extra things from offline.html file which is visible on preview
5. Checklist
6. Screenshots/GIFs
https://github.com/user-attachments/assets/b05737ad-2548-4fb2-b131-0b5edfe6e52e
This video indicates before in rent now button …

Fix: Update 'Rent now' buttons to redirect to rent your car button and remove extra things from offline.html

---

src/assets/styles/style.css
src/index.html

Fixed Footer section of Home Page
Before : 
After :

Fixed Footer section of Home Page

---

ContactUs.html

fix: add proper input validation to form fields
This PR addresses the lack of proper validation in the form.  
Previously, the form allowed submission even when the `Name` or `Message` fields contained only a single character.
This update ensures:
- Minimum character requirements for text fields (Name: at least 3 characters, Message: at least 10 characters).
- Clear error messages for invalid inputs.
These changes improve user experience and prevent incomplete or invalid data from being submitted.
Closes #307

Update Contact Form

---

assets/css/style.css
index.html

This pull request fixes the broken footer on the Home page, where elements were misaligned and overlapping with content in certain viewports.  
The issue was caused by incorrect flexbox alignment and missing responsive styling, leading to layout issues.  
The updated styling ensures the footer stays at the bottom, maintains proper spacing, and remains fully responsive.
Works on both light and the dark theme.
Fixes #242
- Before :
- After : 
<br>

Repair broken footer layout on Home page

---

vehigo-backend/src/controllers/authController.js

Add update profile controller for authenticated users
This pull request introduces a new updateProfile controller that allows authenticated users to update their profile details securely. The controller ensures that only allowed fields are updated, input validation is enforced, and sensitive fields like email and auth_provider remain immutable to maintain account integrity.
Fixes #372 
Created updateProfile controller in controllers/authController.js.
Added Zod validation schema for update requests.
Implemented field restrictions for email and auth_provider.
Added logic to validate phone number and restrict password updates based on auth provider.
Integrated JWT middleware to fetch authenticated user. …

Added a update profile controller

---

src/index.html

feat: enable smooth scroll-to-top on logo click in src/index.html
This pull request implements smooth scrolling to the top of the page when the VehiGo logo is clicked on the `src/index.html` page.  
The change is implemented inline within the page to ensure it only affects this specific page and does not alter the logo behavior on other routes or pages.  
This enhances navigation by allowing users to quickly return to the top without manually scrolling.
Closes #352
>TESTED
https://github.com/user-attachments/assets/fe4ad620-76e9-42f1-ae9f-691702c20027

feat: enable smooth scroll-to-top on logo click in src/index.html

---

offline.html

`fix: Offline center page cards not visible on theme toggle`
This pull request fixes an issue where the cards on the Offline Center page were not visible when toggling from light to dark theme. The root cause was related to CSS variables not updating properly with theme changes. The fix ensures that the card background and text colors respond dynamically to theme toggling, maintaining visibility and readability.
Closes #240

Fix : Offline center page cards to be visible on theme toggle

---

carPage.html
src/assets/styles/carPage.css

Fixed following things of carPage :
1) Fixed Navbar.
2) Fixed UI/UX.
3) Added More Cars.
Before : 
After : 
After Cars  Added :

Fixed carPage

---

src/pages/about.html

Fixed Double navbar bug in About page
Before : 
After :

Fixed Navbar Bug in About page

---

assets/css/style.css
buy.html
featured-car.html
index.html

Description
#385 
UNDER GSSOC2025
The featured-car.html page had a misaligned header and improperly spaced content, making the layout inconsistent compared to other pages. This affected overall design uniformity and user experience.
Steps to Reproduce
Open featured-car.html in a browser.
Compare the header design and alignment with other pages.
Observe that header elements are misaligned and content spacing is inconsistent.
Expected Behavior
Header should match the style and layout of other pages.
All content sections should be properly aligned and evenly spaced.
Page should remain responsive across devices (mobile, tablet, desktop).
Changes Made
Updated header HTML structure to match the global header template used across the site.
Adjusted CSS for margins, padding, and flex/grid …

Fixed Misaligned Header and Content on featured-car.html

---

assets/css/style.css
buy.html
index.html

Description
#384 
UNDER GSSOC2025
The header on the buy.html page was broken and inconsistent with other pages. This caused misalignment and overlapping content, leading to a poor user experience. Additionally, there was a padding issue where text was being hidden beneath the header.
Steps to Reproduce
Open buy.html in a browser.
Compare the header section with other pages.
Notice that header elements are misaligned and overlap with page content.
Expected Behavior
Header should follow the same structure and styling as other pages.
Content should be properly spaced and not hidden beneath the header.
Changes Made
Updated the header HTML structure to match the global template used across other pages.
Fixed CSS spacing and alignment issues for header elements.
Resolved padding issue that …

Fixed Broken Header Design on buy.html Page

---

src/assets/styles/about.css
src/pages/about.html

Description:
#403 
UNDER GSSOC25
Fixed the misaligned/messed-up header section on the About Us page.
Ensured the header layout, spacing, and alignment now match the design of other pages for consistency.
Improved responsiveness so the header displays correctly across devices.
Updated dark theme styles for the About Us header, ensuring proper text contrast, colors, and overall readability.
Changes Made
Adjusted CSS for header alignment, spacing, and typography.
Synced font sizes, weights, and colors with the global header style.
Added dark mode color adjustments to maintain visibility and consistency.
Tested responsiveness for mobile, tablet, and desktop views.
Screenshots:

Fixed Misaligned About Us Header & Dark Theme Support

---

rentcar.html
styles/rentcar-modern.css

Description
UNDER GSSOC25
#419 
FOR BOTH DARK AND LIGHT THEME
This PR refines the Rent Car page by improving the header and content layout for a cleaner and more visually appealing experience.
Changes Made
Fixed header layout to align with global design.
Improved content structure for better readability.
Enhanced spacing, alignment, and styling across sections.
Made overall design more appealing and consistent with other pages.
Screenshots

Enhance Rent Car Page – Header & Content Improvements

---

rentcar.html

This pull request fixes alignment and layout issues on the rent car page.   
- The navbar styling was inconsistent across different screen sizes, causing misalignment.  
- The form on the rent car page was not centered properly, leading to a poor user experience on both desktop and mobile views.  
- These changes ensure a consistent, responsive, and visually appealing layout.

Fix Navbar and Centered the form on Rent Car Page

---

src/assets/styles/about.css
src/pages/about.html

Description
This PR updates the About Us page by adding meaningful content and fixing the broken UI layout. Previously, the page had no content and was misaligned compared to the rest of the site, making it look incomplete and inconsistent.
Changes Made
Added content including:
Short introduction about the website
Mission statement
Fixed layout and alignment issues in the header and container
Improved spacing, typography, and overall responsiveness
Ensured consistency with the design style/theme used across the site
Screenshots

Fixed About Us Page UI & Add Content

---

src/pages/login.html

Fixed Non-working Links of Login page

Fixed Non-working Links of Login page

---

assets/css/style.css
offline.html

Description:
#406 
Fixed the sidebar layout and alignment issues.
Updated the sidebar background color for better UI consistency.
Ensured that the same items are now available in the sidebar for a uniform experience.
Impact:
Improves visual consistency and ensures users have access to the same set of items from the sidebar across the app.

Fixed Sidebar Layout & Background Color

---

index.html
src/pages/about.html

solved issue #449- fixed issue with footer of about us page

solved issue #449- fixed issue with footer of about us page

---

assets/css/style.css
offline.html

Description:
UNDER GSSOC25
#472 
Updated the footer UI of the Offline Centers page to ensure consistency with the rest of the app’s design.
Added icons alongside footer links for better visual representation.
Applied transform effects on icons for smoother interaction.
Improved link alignment and spacing for better readability.
Changes Made:
Footer layout updated to match the global UI style.
Icons integrated into navigation links.
Transform animations added for hover/click effects.
Ensured responsive design compatibility.

Make Footer of Offline Centers Page Consistent with Other Screens

---

src/assets/styles/loginstyle.css
src/pages/login.html

This PR introduces several UI/UX improvements to the login page:
UNDER GSSOC25
#468 
Added a welcome message to make the page more engaging.
Ensured the form is clearly visible with improved layout and spacing.
Applied a border color and styled text fields for better readability and focus.
Added a favicon to the login page for branding and recognition in browser tabs.
Screenshots

UI Improvements: Added Welcome Message, Enhanced Form Visibility, and Favicon

---

src/blog.css

Added hover effects and smooth transitions for various blog elements.
Enhance blog styles with transitions and hover effects
Added the Enhanced blog styles with transitions and hover effects
Fixes #478 
Updated blog.css file

Enhance blog styles with transitions and hover effects

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/Pull_request_template.md

Added Templates for pull request and issues Templates
Provide a detailed description of the changes introduced by this pull request. Explain what was changed and why. Include any relevant context or design decisions.
#477 

Added Templates

---

src/assets/styles/loginstyle.css
src/pages/login.html

Fixed Login Page
Before : 
After :

Fixed Login Page

---

offline.html
src/pages/help-center.html

title=added header in help center 
issue= header in help center is very bad i changed ui according  to theme of web
corresponding issue = #517 
solution=i changed ui of header of help centre 
image
before 
after
review changes and assign changes to me

added header in help centre

---

src/pages/about.html
src/pages/bill.html

Title-rebuilded about.html page
issue number that is associated with this pr= #511  
Issue=when i see about us section every section is overwritten so that i decided to change it
solution=i rebuild about us section that is to good and also good interface and right way to redirect about us section
Screenshots
this is the before when i not changed code as you can see all things are overwritten 
https://github.com/user-attachments/assets/79e55a4d-da12-4480-9f01-d2bccad7c79f
this is after when i change code and rebuild about us section
kindly review changes and assign it issue to me and give level 3 because it takes to much time so please assign it me and give level 3 @Akashshelke07

rebuild about.html page

---

src/pages/help-center.html

Title=
Issue=when i see help centre page there is no login and signup page so i decided to add it here i am attaching one screenshot so that you can check
Solution=i changed some code and changed ui of this so that user option visible and make it clearly and it is redirect correct
Corresponding issue= #519 
this is before image 
https://github.com/user-attachments/assets/6577d5ed-4040-42c7-9ae2-9f6df86543d8
this is video in this video you can see this user login and signup feature i added
so review changes and kindly assign this pr to me and give level 3 or 2 @Akashshelke07

added login button in help centre page

---

assets/css/style.css
index.html

Description
UNDER GSSOC25
#418 
This PR fixes the misaligned header on the main page and ensures it is consistent with headers used across other pages. The update improves visual flow and UI consistency while also maintaining responsiveness across devices.
Changes Made
Adjusted CSS for header alignment and spacing.
Standardized font sizes, weights, and colors to match the global design system.
Fixed responsiveness for different screen sizes.
Applied consistent styling for both dark mode and light mode.
Before & After
Before: Header misaligned, inconsistent font sizing, spacing issues.
After: Header fully aligned, consistent with other pages, responsive in all modes.

Align and Standardize Header Layout on Main Page (Dark & Light Mode Support)

---

src/pages/Askaques.html
src/pages/help-center.html

Title=removed extra thing from background of ask a question
issue=something is written in background of ask a question 
corresponding issue = #521 
solution= i removed this is extra things
before text highlited by red  border
after the change of code
so review changes and assign this pr to me and give level 3 @Akashshelke07

removed extra thing from background of ask a question

---

src/pages/Askaques.html
src/pages/bill.html

Issue=when i see fare calculator option in that section pricing plan option not redirect correctly
Solution=i changed code and now it is redirect correctly 
Corresponding Issue= #532 
https://github.com/user-attachments/assets/dbfd2656-0d85-4f6e-83c5-70fc30427505
before video it shows that not redirect correctly
https://github.com/user-attachments/assets/5132b3bd-9c5e-4704-9c40-70291bf311e6
after video as you can see redirect successfully
so review changes and assign this pr to me and give level 3 or 2 @Akashshelke07

Pricing plan redirect correctly in fare calculator section

---

src/index.html
src/pages/Askaques.html
src/pages/bill.html

Issue=when i  see ask a question section in that section privacy policy not redirect correctly
Solution= i changed code and now it is redirect correctly
Correspoding issue= #534 
https://github.com/user-attachments/assets/e4bf1827-abdb-4428-a42a-6d27d6098a71
before when i not changed code it is not redirect correctly
https://github.com/user-attachments/assets/94b85ffa-391c-4687-8126-f9ddaab53303
after the change o code it is redirect correctly
so review changes and assign this pr to me and give level 3 or 2 @Akashshelke07

privacy policy redirect correctly

---

assets/css/style.css
index.html

Description:
UNDER GSSOC25
#526 
Updated the "Get Started in 4 Steps" boxes to match the dark theme.
Added smooth transitions for better user experience.
Improved the navbar UI to make it more user-friendly and consistent with the dark theme.
Changes Made:
Applied dark theme styling to the "Get Started in 4 Steps" section.
Added hover and transition effects for better interactivity.
Refined navbar layout, spacing, and visual hierarchy for better usability.
Screenshots :

Updated Dark Theme UI for "Get Started in 4 Steps" and Navbar Enhancements

---

src/pages/login.html

- Closes #559 .
This commit adds a new 'Confirm Password' field to the registration form.
The purpose of this feature is to prevent user typos and enhance security during account creation. The form now validates that the 'Password' and 'Confirm Password' fields match, providing immediate feedback and ensuring the user sets the correct password.

Feat: Added confirm password field

---

ContactUs.html
assets/js/script.js
index.html
src/assets/styles/style.css
src/pages/Askaques.html

Issue=when i see footer of index page font of footer colour match with background colour so font not visible properly
solution=i changed colour of this font 
Corresponding Issue= #592 
this is before section that looks like not visible
this is after section that looks good and also visible properly
so reveiw changes and assign this issue to me and give level 3 @Akashshelke07

In index page footer font colour overlap with background colour

---

index.html

Description
UNDER GSSOC25
#585 
This PR fixes the unresponsive Login button and resolves UI inconsistencies across the website. The Login button now redirects users to the login/signup page seamlessly, and the overall UI has been refined for a cleaner look.
Related Issue
Login button not navigating to login/signup page.
Minor UI layout issues.
Type of Change
Bug fix (non-breaking change which fixes an issue)
UI/UX improvement
Changes Made
Fixed the navigation logic for the Login button.
Ensured proper routing to the login/signup page.
Improved UI alignment and styling for consistency.
Added screenshots of the updated design and working navigation.
Steps to Reproduce (Before Fix)
Open the website.
Click on the Login button.
Notice that no navigation occurs.
Expected Behavior (After Fix) …

Login Button now navigating to Login/Signup Page

---

index.html

Description
UNDER GSSOC25
#583 
This PR addresses the issue where the footer content was not clearly visible in light mode, leading to poor readability and inconsistency with the dark mode design.
Changes Made
Updated footer text and background colors to maintain proper contrast in light mode.
Ensured footer styling remains consistent between light and dark modes.
Verified that the new colors meet accessibility contrast ratio standards.
Screenshots:
Before:
After:

Improve footer visibility in light mode for better readability

---

src/assets/styles/about.css
src/pages/about.html

Changes Made
UNDER GSSOC25
#530 
Replaced the About page navbar with the updated version from the Index page.
Ensured all links are functional and redirect correctly.
Standardized typography, spacing, and styles to align with the global theme.
Improved responsiveness for mobile and tablet view.
Verified light/dark mode compatibility with the global theme.
Visual Improvements
Navbar on About page now matches the Index page for a consistent browsing experience.
All buttons, links, and hover states behave the same across pages.
Testing Done
All links verified and working.
Responsive layout checked (desktop, tablet, mobile).
Dark mode and light mode tested.
Cross-checked styling with Index page.
Screenshots

Updated About Page Navbar for Consistency

---

index.html

Pull Request: Fix Homepage Padding Issue (#622)
Summary: This PR resolves the lack of padding on the homepage by introducing consistent spacing across key sections, improving visual hierarchy and readability.
Changes Made:
Added padding-inline and padding-block to the main homepage container
Ensured responsive spacing using clamp() for scalable design
Audited nested components to prevent overflow or double-padding
Verified alignment with existing layout grid and spacing tokens

fix: add responsive padding to homepage container (#622)

---

src/assets/styles/about.css
src/pages/about.html

Fixed About us page navbar
Before : 
After :

Fixed About us page navbar

---

blog.html
tandc.html

@Akashshelke07 you said to resolve the merge conflict of pr #617 so i couldfind error in that so i decided to send new pr of that pr and some more changes 
@Akashshelke07 also give tag and level in one pr that you closed i gauss you forget to give pr number = #603 
so @Akashshelke07 review and close both pr and also give level 3 because you give level 3 in pr #617 so closed both pr

resolve merge conflict of pr #617 and some small changes

---

src/assets/styles/about.css
src/pages/about.html

Description:
UNDER GSSOC25
#632 
The header on the About Us page was inconsistent with the updated home screen design, leading to a lack of visual flow and professionalism.
This PR updates the About Us header to align with the home screen header, ensuring consistency across the site.
Changes Made:
Redesigned the About Us header to match the home screen in terms of:
✅ Typography
✅ Color scheme
✅ Spacing and padding
✅ Component styling
Fixed all navigation links for smooth redirection across pages.
Removed unnecessary CSS files that were previously linked but not used.
Ensured responsive design compatibility across desktop, tablet, and mobile devices.
Steps to Test:
Visit the Home screen and note the header style.
Navigate to the About Us page.
Confirm that the header design now matches the …

Updated About Us Page Header to Match Home Screen Design

---

privacypolicy.html

Fixes #639 
Privacy Policy was already connected in the footer, so updated the privacy policy page by making its footer symmetrical to that of the terms and condition page
INITIALLY (attached above)
Made footer symmetrical to the terms and condition page

ISSUE #639

---

ContactUs.html

ISSUE #641

---

src/assets/styles/loginstyle.css
src/pages/login.html

- Closes #628 
Password checklist helps users create a strong password.
Added a password validation check in order to create standard strong passwords.
Changes are tested locally.

Added a password checklist for sign up page

---

privacypolicy.html

Issue=header of privacy policy not visible 
solution=i changed it and now it is ready
Corresponding Issue= #669 
before
after 
kindly review changes and assign this issue to me and give level 3 or level 2 @Akashshelke07

changed header of privacy policy

---

index.html
privacypolicy.html

Issue=there is no chatbot in whole web
Solution=i added it and now it works clearly
Corresponding Issue= #673 
as you can see in image chatbot work properly
so review changes and assingnn this issue to me and give level 3 because it take too much time for code i hope you can understand so give level 3 @Akashshelke07

Added chatbot in home page

---

blogs/blog1.html
blogs/blog2.html
blogs/blog3.html
blogs/blog4.html
blogs/blog5.html
index.html
privacypolicy.html

Issue=in our blog every blog return me not redirect 
Solution=i changed code and now it redirect correctly
Corresponding issue= #676 
https://github.com/user-attachments/assets/2b6de482-a0ce-4c0f-8bed-f58eacd69d2c
before
https://github.com/user-attachments/assets/4462b027-6a77-4cb6-932e-59f898548081
after
so kindly review changed and assign this pr to me and givel level 3 or 2 @Akashshelke07

Back to blog redirect correctly

---

ContactUs.html
buy.html
featured-car.html
index.html
offline.html
src/pages/about.html
src/pages/login.html

This PR resolves critical navigation and content display issues in the "Explore cars" section across the entire website, ensuring users can properly browse and access car listings.
The Explore cars functionality had multiple critical issues:
- Homepage showed placeholder content instead of actual car listings
- Navigation links were broken or inconsistent across different pages
- "Rent now" buttons were non-functional
- Duplicate car entries in featured cars page
- Users couldn't properly navigate to or from the car browsing section
- **Fixed JavaScript Loading**: Added proper car data loading after skeleton animation
- **Real Content Display**: Homepage now shows actual car listings with images, details, and pricing
- **Proper Data Rendering**: Cars are displayed with correct information …

fix: resolve Explore cars navigation issues across all pages Fixes #688

---

rentcar.html
scripts/rentcar.js

Issue= ui of rent your car not match with project ui 
Solution=ii change it and now it is match
Corresponding Issue= #706 
i could not upload photo due to some issue so understand take preview of this so that you ensure about this 
so kinfly assign this pr to me and give level 3 @Akashshelke07

changed ui of rent your car page

---

index.html
rentcar.html
scripts/rentcar.js

issue = box border not visible in dark mode
Solution= i changed box colour to white so that it visible clearly
Corresponding Issue = #711 
before
after 
so review changes and assign this pr to me and give level 3 or 2 @Akashshelke07

changed box border colour

---

index.html
rentcar.html
scripts/rentcar.js

Issue= chatbot funcionality not working
Solution= i created  a whole java script functionality for chatbot 
Corresponding Issue= #713 
https://github.com/user-attachments/assets/a092695e-0cdf-4b3a-84af-877d646a2ec7
before
https://github.com/user-attachments/assets/908a903a-c607-451a-8459-b32d50641203
after
so review changes and assign this pr to me and give level 3 because it take time to create java script functionality

added functionality for chatbot so that it works correct

---

index.html
registrationPage.html
rentcar.html
scripts/rentcar.js
src/assets/styles/loginstyle.css
src/pages/login.html
styles/registrationStyle.css

Issue- there is no terms and condition accept checkbox
Solution= i created this checkbox aftert the accept of this then and then it signup 
Corresponding Issue= #715 
https://github.com/user-attachments/assets/5f4b7681-993f-4c49-ad4d-5020c9f537f4
so review changes and assign this pr to me and give level 3 @Akashshelke07

Added checkbox in signup page so that user accept terms and condition

---

blog.html
index.html
registrationPage.html
rentcar.html
scripts/rentcar.js
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/registrationStyle.css

Issue== there are no dark mode in helpcenter page
Solution= i implement  it dark mode now appear in help centre page
Correspndding Issue= #719 
https://github.com/user-attachments/assets/be889608-0a74-43c9-a785-2203ed1b24ef
review changes and assign this pr to me and give level 3 because dark mode implement take time whole feature implement is har i hope you understand so give level 3 @Akashshelke07

Added dark mode in  help centre page

---

blog.html
index.html
registrationPage.html
rentcar.html
scripts/rentcar.js
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/registrationStyle.css

Issue = in home page footer of home page in part services in web written as signup but it redirect to login 
Solution=i think we have to make same name as link so i changed it
Corresponding Issue= #723 
https://github.com/user-attachments/assets/d76c3504-c17f-47fa-8e35-0f20d8e73aee
before as you can see what is written and what is redirect
after as you can see login redirect to login 
so review changes and assignn this pr to me and give level 2 @Akashshelke07

Correction in home page link redirect to login but written signup 

---

blog.html
index.html
registrationPage.html
rentcar.html
scripts/rentcar.js
sitemap.html
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/registrationStyle.css

Issue- when i see homepage then click on sitemap it redirect but no thing appear at that time i understand no one will create this but create just a button
Solution= i created sitemap.html page
Corresponding Issue= #725 
https://github.com/user-attachments/assets/35d1ab48-0f45-415d-b986-4a1c57cb07d9
as you can see in video i builded whole page 
so review changes and assign this pr to me and give level 3 because i created almost 400 lines of code i hope you can understand so give according to this level 3 @Akashshelke07

Builded sitemap.html page

---

blog.html
index.html
offline.html
registrationPage.html
rentcar.html
scripts/rentcar.js
sitemap.html
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/offline.css
styles/registrationStyle.css

Issue = ui of footer of offlien.html page not match with project ui
Solution= i changed it and now it match with project ui
Corresponding Issue = #727 
before
after 
kindly review changes and assign this pr to me and give level 3 or 2 @Akashshelke07

Changed ui of footer of offline.html page

---

blog.html
index.html
offline.html
registrationPage.html
rentcar.html
scripts/rentcar.js
sitemap.html
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/offline.css
styles/registrationStyle.css

Issue=button of theme change in offline.html page not work error is that just button crreated not fuctionality
solution=i changed code and now it working
Corresponding Issue = #729 
https://github.com/user-attachments/assets/554dfcb2-b086-43f7-80c8-aae2bb2c04e5
before
https://github.com/user-attachments/assets/f577656b-ad91-4ec4-b8ed-cdb17e0c070e
after 
kindly review changes and assign this pr to me and give level 3 because whole theme code generated hope you understand and give level 3 @Akashshelke07

making button working of theme in offline.html page

---

blog.html
feedbackForm.html
index.html
offline.html
registrationPage.html
rentcar.html
scripts/rentcar.js
sitemap.html
src/assets/styles/loginstyle.css
src/pages/help-center.html
src/pages/login.html
styles/offline.css
styles/registrationStyle.css

Issue= ui of feedback form is very normal
Solution= i changed ui and now it looks amazing
Corresponding Issue = #731 
before 
https://github.com/user-attachments/assets/7117542d-0bd1-4488-9b0e-35b4aa004e50
after as you can see ui  is imroved
so kindly review changes and assign this pr to me and give level 3 or 2 @Akashshelke07

Improve UI of feedbackform 

---

blog.html
feedbackForm.html
index.html
offline.html
privacypolicy.html
registrationPage.html
rentcar.html
scripts/rentcar.js
sitemap.html
src/assets/styles/loginstyle.css
src/pages/about.html
src/pages/help-center.html
src/pages/login.html
styles/offline.css
styles/registrationStyle.css

Issue= header of privacy policy moved slightly right side so that login and light button not visible
Solution=i created code so that header come in centre also login and light button both working
Corresponding Issue= #735 
before
after
so review changes and assign this pr to me and give level 3 or  2 @Akashshelke07

changed ui of header of privacy policy page

---

src/pages/about.html

Description:
UNDER GSSOC25
#695 
This PR resolves an issue where Navbar links on the About Us screen were not functioning as expected. Previously, navigating to other pages (e.g., Home, Contact, Services) caused broken routes or unexpected behavior.
Changes Made:
Fixed route mapping in the Navbar component.
Ensured that all Navbar links redirect correctly when accessed from the About Us screen.
Verified smooth navigation flow across all screens.
Steps to Test:
Pull the branch and run the app.
Navigate to the About Us screen.
Use the Navbar to go to different pages (Home, Contact, Services, etc.).
Confirm that each link redirects properly without errors.
Expected Behavior:
All Navbar links should work consistently across all screens, including About Us.
Users should experience smooth and …

Fixed Navbar Navigation from About Us Screen

---

index.html

This PR addresses critical visibility issues in dark mode on the home page, improving user experience and accessibility.
- **Logo Visibility**: Fixed dull logo appearance in dark mode
- **Input Placeholder Text**: Made placeholder text visible in search form fields
- **Form Labels**: Enhanced contrast for better readability
- **Search Form Background**: Improved overall contrast and visibility
```css
.dark-theme .navbar-brand img {
filter: brightness(0) invert(1);
opacity: 1;
transition: opacity 0.3s ease;
}
.dark-theme .navbar-brand:hover img {
opacity: 0.8;
}
```
```css
.dark-theme .form-control::placeholder {
color: rgba(255, 255, 255, 0.7) !important;
opacity: 1 !important;
}
.dark-theme .form-select::placeholder {
color: rgba(255, 255, 255, 0.7) !important;
opacity: 1 !important;
} …
```

Fix dark mode visibility issues issue #738

---

src/pages/Askaques.html

- Closes #782
The footer section had alignment and styling issues:
- Social icons were stacking vertically instead of displaying in a row.
- Copyright text and icons were not properly aligned.
Updated the footer layout to use flexbox for proper alignment.
Moved copyright text to the right and social icons to the right in a single row.
Applied brand colors to social media icons.
Added a white background to the inner footer section for better contrast.
- Yes, the changes were manually tested across multiple browsers and screen sizes.
- Verified that the footer alignment works correctly.
- Checked that the white background is applied only to the inner footer box without affecting the rest of the footer.
Yes.
- Footer layout is now cleaner and more professional.
- Copyright text and social …

Changed the footer layout in Ask a Question page

---

src/assets/styles/about.css
src/pages/about.html

This PR addresses issue #710.
Originally, during the live demo, clicking on the About Us button in the navbar did not navigate to a separate section. However, upon cloning the repo, the website already had a modified version with an About Us section.
Therefore, this PR focuses on the following improvements to the About Us page:
Fixed card alignment to ensure consistent layout [Team information cards]
Added a Contributors section for better visibility of team members
Made small UI refinements to improve overall look and feel of the page
These changes enhance the user experience and maintain design consistency across the site.
- Closes #.
Bug fix (UI alignment)
Improvement (UI/UX refinements)
New feature (Contributors section)
Verified card alignment visually across different screen sizes …

Enhance About Us Page – Fix Card Alignment, Add Contributors Section, and UI Refinements (#710)

---

index.html
sitemap.html

Issue= theme change button of sitemap page not working
Solution= i make it correct by removing some code
Corresponding Issue= #813 
https://github.com/user-attachments/assets/cc808a17-56c4-4661-928c-547306724cbb
kindly review changes and assign this pr to me and give level 3 @Akashshelke07

solving the error of theme change  button of sitemap page

---

index.html

Issue = language feature is not working
Solution= i made it
Corresponding Issue= #811 
https://github.com/user-attachments/assets/f2ca06d5-2858-417c-871d-9281ed5ba3af
as you can see in video now it is working 
so assign this pr to me and give level 3 @Akashshelke07

added language feature

---

index.html

Issue= i can see there is need of dropdown menu
Solution= i added dropdown with 10 city for reference
Corresponding Issue= #818 
kindly review changes and assign this pr to me and give level 3 @Akashshelke07

added dropdown in index at location

---

assets/css/dark.css

Fix the text visibility on  Cars Cards 

---

assets/css/blog-enhanced.css
assets/css/blog-post.css
blog.html
blogs/blog1.html
blogs/blog2.html
blogs/blog3.html
blogs/blog4.html
blogs/blog5.html

Redesigned the Blogs  pages

---

src/pages/pricing.html

- Updated footer CSS to align all links in a single line
- Improved spacing and consistency of footer section on pricing.html
- Footer links appeared in multiple lines, breaking alignment.
- Footer links now appear in one clean line with proper spacing.

Fix Footer alignment of pricing.html page

---

src/pages/about.html
src/pages/pricing.html

Fixes #839
- Added CSS to `.testimonials-container`:
- `overflow-x: auto` for horizontal scrolling
- `padding-right: 1rem` to prevent last card cutoff
- `scroll-behavior: smooth` for better UX
The last customer testimonial (Prateeksha J...) is now fully visible and scrollable in the "What Our Customers Say" section.

Last customer testimonial card not fully visible in "What Our Customers Say" in about.html

---

ContactUs.css
ContactUs.html
ContactUs.js

Enhanced the contact form with comprehensive client-side validation and improved accessibility features. This update provides users with immediate, helpful feedback when filling out the form, making it more user-friendly and reducing submission errors.
This enhancement improves the overall user experience of the contact form, addressing potential usability issues where users might submit invalid data without knowing what went wrong.
Tested the form with various inputs:
- Valid names, emails, and messages submit successfully
- Invalid inputs (short names, malformed emails, empty messages) show appropriate error messages
- Error messages clear when users correct their input
- Form works correctly in both light and dark modes
- Accessibility features verified (keyboard navigation, screen …

Improve Contact Form Validation and Accessibility

---

src/pages/about.html

#835 fixed
- Removed duplicate set of social media icons from about.html footer
- Now only one set of icons is displayed correctly

Footer social icons not displaying correctly in about.html page displayed twice 

---

blog.html
src/pages/about.html

#831 fixed
This pr fixes the social media icons (Facebook, Instagram, Twitter, LinkedIn, GitHub, etc.) in the footer were not displayed correctly and showed only empty square placeholders.
**Changes Made**
Corrected the icon references so that all footer social media icons are visible.
Ensured consistent alignment and styling across all icons.
**Expected Behavior**
Icons now display properly (Facebook, Instagram, Twitter, LinkedIn, GitHub).
Footer looks consistent with the design.

Footer social media icons not showing featured-car.html page

---

src/pages/login.html

Which issue does this PR close?
Closes #856.
Rationale for this change
The input type for the phone number field on the signup page was previously set to number. This is not the ideal type for phone numbers as it can restrict input formats (e.g., removing leading zeros or disallowing characters like +, -, (, )).
Changing the type to tel provides a better user experience, especially on mobile devices. It brings up a telephone-specific keypad, which includes numbers and common special characters used in phone numbers, making data entry faster and more intuitive for the user. This change also improves the semantic correctness of our HTML.
What changes are included in this PR?
This PR includes a single, targeted change:
In the signup page component, the input element for the user's phone …

Changed the phonenumber field to tel

---

src/assets/styles/about.css
src/pages/about.html

Fixed About Us page
Before :
After :

Fixed About Us page

---

rentcar.html

- Closes #809 
---
The current "Add Your Vehicle" form had several usability and design issues:
- Inputs were aligned horizontally, causing a cluttered and congested layout.
- Lack of clear visual hierarchy made labels, placeholders, and fields blend together.
- No separation between fields, making the form hard to read.
- Button styling was basic and did not stand out.
- The form was not fully responsive on smaller screens.
This PR redesigns the form to be **vertical, modern, and user-friendly**, improving readability, usability, and responsiveness.
---
- Redesigned the form to use a **vertical layout** with proper spacing between inputs.
- Added a **card-style container** with padding, rounded corners, and shadow effects.
- Improved placeholder text and labels for better clarity.
- …

redesign Add Your Vehicle form

---

index.html

Issue=chatbot not working 
Solution= i made working of this by adding some missing script in this code of chatbot
as you can see in image now chatbot working properly
so kindly review changes and assign this pr to me and give level 3 because it takes time to understand issue i hope you understand and give level 3 @Akashshelke07

make working of chatbot

---

index.html

- Closes #897 
fixes logo and few layout related issues
just removed incomplete code blocks to fix layout issue
yes

minor-layout-fixes

---

src/assets/styles/style.css
src/index.html

Fixed the Order of all things in Index Page.
=> Filter was at the Last, FAQ was at at First, and all other things were orderless, So Fixed them in Correct Order.
( All Images are at 80% Web view, for easier understanding )
Before : 
<br>
<br>
After :

Fixed the Index Page
